//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlinePlatby.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int PaymentTypeId { get; set; }
        public int CurrencyId { get; set; }
        public int OrderStateId { get; set; }
        public int TransportId { get; set; }
        public int DeliveryAddressId { get; set; }
        public int BillingAddressId { get; set; }
        public string IPAddress { get; set; }
        public decimal CostWithoutTax { get; set; }
        public decimal CostWithTax { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public decimal PaymentTypeFee { get; set; }
        public decimal TransportFee { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual OrderState OrderState { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual Transport Transport { get; set; }
    }
}
