//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlinePlatby.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVariant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductVariant()
        {
            this.DigitalProducts = new HashSet<DigitalProduct>();
            this.ProductAttachments = new HashSet<ProductAttachment>();
            this.PropertyCombinations = new HashSet<PropertyCombination>();
            this.Baskets = new HashSet<Basket>();
            this.ProductCategories = new HashSet<ProductCategory>();
            this.Images = new HashSet<Image>();
        }
    
        public int Id { get; set; }
        public int ProductId { get; set; }
        public string UniqueCombination { get; set; }
        public Nullable<int> ProductStateId { get; set; }
        public Nullable<int> MainImageId { get; set; }
        public int PurchasePriceCurrencyId { get; set; }
        public int SalePriceCurrencyId { get; set; }
        public int RecommendedPriceCurrencyId { get; set; }
        public decimal PurchasePrice { get; set; }
        public decimal RecommendedPrice { get; set; }
        public decimal SalePrice { get; set; }
        public string Code { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Currency Currency1 { get; set; }
        public virtual Currency Currency2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DigitalProduct> DigitalProducts { get; set; }
        public virtual Image Image { get; set; }
        public virtual Product Product { get; set; }
        public virtual ProductState ProductState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductAttachment> ProductAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyCombination> PropertyCombinations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basket> Baskets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCategory> ProductCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
    }
}
